name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "roblowe8" --password-stdin
        docker buildx build --platform linux/arm/v7 -t roblowe8/docker-compose-heyu-mqtt:armv7 .
        docker push roblowe8/docker-compose-heyu-mqtt:armv7
#        docker buildx build -t roblowe8/docker-compose-heyu-mqtt .
#        docker push roblowe8/docker-compose-heyu-mqtt
